ALTER TABLE "MeterWhitelist"
ADD COLUMN "discount" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "lastBalance" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "paidAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "arrears" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "reconnectionFee" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "deposit" DECIMAL(14,2) NOT NULL DEFAULT 0;

ALTER TABLE "BillerTransaction"
ADD COLUMN "address" TEXT,
ADD COLUMN "billCode" TEXT,
ADD COLUMN "dueDate" TIMESTAMP(3),
ADD COLUMN "powerFee" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "discount" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "lastBalance" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "paidAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "arrears" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "reconnectionFee" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "deposit" DECIMAL(14,2) NOT NULL DEFAULT 0;
